repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: git://github.com/awebdeveloper/pre-commit-tslint/
    rev: '0.0.2'  # Use the sha or tag you want to point at
    hooks:
    -   id: tslint
        args: ['--project','tsconfig.testing.json','--type-check']
